Fix #299, Sleep before exit when printing
nasa/PSP pull request #301
Opened 2021-08-29 10:04 UTC by pavll

**Describe the contribution**
- Fixes #299 

**Expected behavior changes**
- Print before exit [#299]

**Additional context**
- Considering if 100 milliseconds would be better than 1000 to save time and have a print.
- Considering fflush(stdout) instead of OS_TaskDelay

**Contributor Info - All information REQUIRED for consideration of pull request**
Paul Oberosler, Individual

2021-09-01 15:31 UTC, jphickey requested changes
This has come up a time or two, the root of the problem is really that OS_printf is now always associated with a background task/local OSAL bufffer to do the output.  This makes it so its always buffered consistently across platforms.

The price of that consistency, is that in previous versions, OS_printf on POSIX was just directly going to the libc printf, but now it's got an extra buffer in the middle.

Rather than adding a blanket delay - which is not ideal as its much longer than it really needs to be, while also not even guaranteeing that the output was flushed - since this is the PC-Linux PSP, and therefore known to be running on this platform, we should be using some form of `perror` here, or at least converting to `fprintf(stderr, ...`.

Note that stderr stream is unbuffered, so there should not be any problem with immediately calling `exit()` afterwards.

2021-09-01 15:33 UTC, jphickey commented
Another option/suggestion would be to use the `CFE_PSP_Panic` function instead of exiting immediately from here.  It's not much better as it stands (it still just does an abort, does not flush the OS_printf queue either) but at least it could provide a single point for doing so, rather than sprinkling OS_TaskDelay everywhere.

2021-09-01 15:37 UTC, jphickey commented
Also note that if we are touching these error message, I would like to see it report the actual errno in some form (at least the number, but preferably the string as obtained from `strerror()` or `perror()`).  These error messages as they stand are too vague to be useful.  While I realize this wasn't part of the original bug, this would be a good improvement IMO if we are touching the lines anyway.

2021-09-01 15:50 UTC, jphickey commented
FYI: I wrote issue #302 so as to not forget about this, it doesn't have to be part of this PR necessarily.

2021-09-20 21:10 UTC, skliper commented
I like the CFE_PSP_Panic suggestion...

2021-09-20 21:12 UTC, skliper reviewed
I like the CFE_PSP_Panic suggestion to replace the OS_TaskDelay and exit.

2021-09-21 20:30 UTC, pavll commented
Ok, thanks for all the information. I have now used CFE_PSP_Panic as well as perror to handle the error.
Perror should now do an output in the following format: "<custom output from previous developer>: <system error message for the last syscall>" 
Does this meet your requested changes?

2021-09-22 16:50 UTC, jphickey approved these changes
Changes look good!

Only required cleanup now is to squash down the multiple commits and rewrite the log message for merging.

2021-09-22 18:47 UTC, pavll commented
> Changes look good!

Ok, great.

> Only required cleanup now is to squash down the multiple commits and rewrite the log message for merging.

Of course, it is already done. I will push it right away.

2021-12-06 19:22 UTC, merged